#!/bin/bash
# memory-check: brain is a muscle, i think

MEMORY_FILE="$HOME/Documents/share/memory-check.gpg.gpg"

RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${RED}👩 Babe! It's 4pm, time for your memory check!${NC}"
echo
echo -e "${YELLOW}🥀 yes honey...${NC}"
echo

gpg -d --no-symkey-cache "$MEMORY_FILE" 2> /dev/null | gpg -d --no-symkey-cache 2> /dev/null || (echo -e "${RED}🤥 MEMORY TEST FAILED${NC}" && exit 1)
