#!/bin/bash

condition=3

RED='\033[1;31m'
NC='\033[0m'

echo -e "${RED}🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭        DON'T PRESS THAT KEY!!!         🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭        DON'T PRESS THAT KEY!!!         🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭        DON'T PRESS THAT KEY!!!         🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭        DON'T PRESS THAT KEY!!!         🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭        DON'T PRESS THAT KEY!!!         🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭        DON'T PRESS THAT KEY!!!         🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭        DON'T PRESS THAT KEY!!!         🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭        DON'T PRESS THAT KEY!!!         🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭${NC}"
echo -e "${RED}🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭🌭${NC}"

sleep $condition
