#!/bin/bash

dir="$HOME/.local/drive/code/venv"
venv=`find $dir -maxdepth 1 -mindepth 1 -type d |\
    tr '\n' '\0' |\
    xargs -0 -n 1 basename |\
    rofi -dmenu -p "venv" 2> /dev/null`

[[ -z $venv ]] && exit

source "$dir/$venv/bin/activate"
