#!/bin/bash

usage() {
    echo "Usage: $0 [VIDEO]"
}

if [[ -z $1 ]]; then
    echo "$0: Please provide an video file."
    usage
    exit
fi

X_FACTOR=128
X_SIZE_FACTOR=4
Y_FACTOR=128
Y_SIZE_FACTOR=88
Y_OFFSET=$((1080/4))

dimension=`ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 "$1"`
width=` echo $dimension | sed -r 's/^([0-9]+)x[0-9]+$/\1/'`
height=`echo $dimension | sed -r 's/^[0-9]+x([0-9]+)$/\1/'`

start_x=$((width*X_SIZE_FACTOR/X_FACTOR))
size_x=$((width-2*start_x))
start_y=$((height*Y_SIZE_FACTOR/Y_FACTOR))
size_y=$((height*$((Y_FACTOR-Y_SIZE_FACTOR-height/Y_OFFSET))/Y_FACTOR))

filename=$(basename -- "$1")
name="${filename%.*}"
ext="${filename##*.}"
output="${name}_blur.${ext}"

ffmpeg -i "$1" \
    -filter_complex "[0:v]crop=${size_x}:${size_y}:${start_x}:${start_y},avgblur=9[fg];[0:v][fg]overlay=${start_x}:${start_y}[v]" \
    -map "[v]" \
    -map 0:a \
    -c:a copy \
    -c:s copy \
    -movflags faststart \
    "$output"
