#!/bin/bash

# htm: unpack zip of webp into directory of jpg

set -e

if [ $# -lt 1 ]; then
    echo "Please provide a zip file."
    echo "USAGE: $(basename $0) [ZIP]"
    exit
fi

zipfull="$@"
filename=${zipfull%.*}

mkdir -p "$filename"

extension="${zipfull##*.}"
if [ "${extension}" != "zip" ] && [ "${extension}" != "cbz" ]; then
    echo "Please provide a zip file."
    echo "USAGE: $(basename $0) [ZIP]"
    exit
fi

# temporary directory
tempdir="/tmp/htm-convert"
rm -rf "$tempdir"
mkdir -p "$tempdir"

unzip "$zipfull" -d "$tempdir"

mogrify -verbose -format jpg -path "$filename" "$tempdir/*.webp"
