#!/usr/bin/python3
# inject javascript into mokuro html
# https://github.com/kha-white/mokuro/issues/16#issuecomment-1690310509

import sys


SCROLL_SPEED = '0.4'
VIM_INJECTION_SITE = 'function onKeyDown(e){var x=0,y=0,z=0;if(e.keyCode===38){y=1}else if(e.keyCode===40){y=-1}else if(e.keyCode===37){x=1}else if(e.keyCode===39){x=-1}else if(e.keyCode===189||e.keyCode===109){z=1}else if(e.keyCode===187||e.keyCode===107){z=-1}if(filterKey(e,x,y,z)){return}'

INJECTION_VIM = f'function onKeyDown(e){{var x=0,y=0,z=0;if(e.keyCode===75){{y={SCROLL_SPEED}}}else if(e.keyCode===74){{y=-{SCROLL_SPEED}}}else if(e.keyCode===72){{x={SCROLL_SPEED}}}else if(e.keyCode===76){{x=-{SCROLL_SPEED}}}else if(e.keyCode===189||e.keyCode===109||e.keyCode===40||e.keyCode===83){{z=1}}else if(e.keyCode===187||e.keyCode===107||e.keyCode===38||e.keyCode===87){{z=-1}}if(filterKey(e,x,y,z)){{return}}'

PANZOOM_INJECTION_SITE = 'pz = panzoom(pc, {'
INJECTION_PANZOOM = """pz = panzoom(pc, {
        bounds: true,
        boundsPadding: 0.05,
        maxZoom: 10,
        minZoom: 0.1,
        zoomDoubleClickSpeed: 1,
        enableTextSelection: true,

        // add this option
        filterKey: function( e, dx, dy, dz ) {
            // don't let panzoom handle this event:
            return true;
        },"""

WHEEL_INJECTION_SITE = 'beforeWheel: function (e) {'
INJECTION_WHEEL = """beforeWheel: function (e) {
            let shouldIgnore = disablePanzoomOnElement(e.target);
            return true;
        },"""

KEYBOARD_INJECTION_SITE = "document.addEventListener('keydown', function onEvent(e) {"
INJECTION_KEYBOARD = """document.addEventListener("keydown", function onEvent(e) {
    switch (e.key) {
        // change to any key you want
        case "ArrowRight":
            prevPage();
            break;

        case "ArrowLeft":
            nextPage();
            break;

        case "d":
            prevPage();
            break;

        case "a":
            nextPage();
            break;

        case "F":
            zoomFitToWidth();
            break;

        case "f":
            zoomFitToScreen();
            break;

        case " ":
            nextPage();
            break;

        case "Backspace":
            prevPage();
            break;

        case "0":
            firstPage();
            break;

        case "1":
            lastPage();
            break;

        case ".":
            zoomDefault();
            break;
    }
});"""


def name():
    return sys.argv[0].split("/")[-1]

def help():
    print(f'Usage: {name()} [MOKURO HTML]')
    print('Injects javascript into mokuro html file.')

def main():
    if '-h' in sys.argv or '--help' in sys.argv:
        help()
        exit(0)

    if len(sys.argv) < 2:
        print(f'{name()}: ERROR Please provide a mokuro html file.')
        print()
        help()
        exit(1)

    html = ''
    try:
        with open(sys.argv[1], 'r') as f:
            html = f.read()
    except:
        print(f"{name()}: ERROR Unable to open file '{sys.argv[1]}'.")
        exit(1)


    # ===================== disable scroll wheel =================================
    wheel = html.split(WHEEL_INJECTION_SITE)
    if len(wheel) != 2:
        print(f"{name()}: ERROR '{sys.argv[1]}' is likely not a mokuro html file.")
        exit(1)
    html = wheel[0] + INJECTION_WHEEL + '\n' +  '\n'.join(wheel[1].split('\n')[4:])
    # =============================================================================

    # ========================= disable panzoom ===================================
    # panzoom = html.split(PANZOOM_INJECTION_SITE)
    # if len(panzoom) != 2:
    #     print(f"{name()}: ERROR '{sys.argv[1]}' is likely not a mokuro html file.")
    #     exit(1)
    # html = panzoom[0] + INJECTION_PANZOOM + '\n' +  '\n'.join(panzoom[1].split('\n')[7:])
    # =============================================================================

    # ========================= keyboard shortcuts ===================================
    keyboard = html.split(KEYBOARD_INJECTION_SITE)
    if len(keyboard) != 2:
        print(f"{name()}: ERROR '{sys.argv[1]}' is likely not a mokuro html file.")
        exit(1)
    html = keyboard[0] + INJECTION_KEYBOARD + '\n' + '\n'.join(keyboard[1].split('\n')[23:])
    # ================================================================================

    # ========================= vim navigation shortcuts =============================
    vim = html.split(VIM_INJECTION_SITE)
    if len(vim) != 2:
        print(f"{name()}: ERROR '{sys.argv[1]}' is likely not a mokuro html file.")
        exit(1)
    html = vim[0] + INJECTION_VIM + vim[1]
    # ================================================================================

    dir_split = sys.argv[1].split('/')
    if len(dir_split) < 2:
        save_name = f'injected-{dir_split[0]}'
    else:
        save_name = f'{"/".join(dir_split[:-1])}/injected-{dir_split[-1]}'

    with open(save_name, 'w') as f:
        f.write(html)

    print(f"Saved to '{save_name}'")


if __name__ == '__main__':
    main()
