#!/usr/bin/python3
# inject javascript into mokuro html
# inspired by: https://github.com/kha-white/mokuro/issues/16#issuecomment-1690310509

import sys


# Default Settings
SCROLL_SPEED = '3'
BACKGROUND_COLOR = '2b2a33'
READING_MODE = "keep zoom, go to top"

BACKGROUND_INJECTION_SITE = "backgroundColor: '#C4C3D0',"
INJECTION_BACKGROUND = f"backgroundColor: '#{BACKGROUND_COLOR}',"

READING_MODE_INJECTION_SITE = "defaultZoomMode: 'fit to screen',"
INJECTION_READING_MODE = f"defaultZoomMode: '{READING_MODE}',"

EDITABLE_INJECTION_SITE = "editableText: false,"
INJECTION_EDITABLE = "editableText: true,"

VIM_INJECTION_SITE = 'function onKeyDown(e){var x=0,y=0,z=0;if(e.keyCode===38){y=1}else if(e.keyCode===40){y=-1}else if(e.keyCode===37){x=1}else if(e.keyCode===39){x=-1}else if(e.keyCode===189||e.keyCode===109){z=1}else if(e.keyCode===187||e.keyCode===107){z=-1}if(filterKey(e,x,y,z)){return}'
INJECTION_VIM = f'function onKeyDown(e){{var x=0,y=0,z=0;if(e.keyCode===75){{y={SCROLL_SPEED}}}else if(e.keyCode===74){{y=-{SCROLL_SPEED}}}else if(e.keyCode===72){{x={SCROLL_SPEED}}}else if(e.keyCode===76){{x=-{SCROLL_SPEED}}}else if(e.keyCode===189||e.keyCode===109||e.keyCode===40||e.keyCode===83){{z=1}}else if(e.keyCode===187||e.keyCode===107||e.keyCode===38||e.keyCode===87){{z=-1}}if(filterKey(e,x,y,z)){{return}}'

PANZOOM_INJECTION_SITE = 'pz = panzoom(pc, {'
INJECTION_PANZOOM = """pz = panzoom(pc, {
        bounds: true,
        boundsPadding: 0.05,
        maxZoom: 10,
        minZoom: 0.1,
        zoomDoubleClickSpeed: 1,
        enableTextSelection: true,

        // add this option
        filterKey: function( e, dx, dy, dz ) {
            // don't let panzoom handle this event:
            return true;
        },"""

WHEEL_INJECTION_SITE = 'beforeWheel: function (e) {'
INJECTION_WHEEL = """beforeWheel: function (e) {
            let shouldIgnore = disablePanzoomOnElement(e.target);
            return true;
        },"""

KEYBOARD_INJECTION_SITE = "document.addEventListener('keydown', function onEvent(e) {"
INJECTION_KEYBOARD = """document.addEventListener("keydown", function onEvent(e) {
    switch (e.key) {
        // change to any key you want
        case "ArrowRight":
            prevPage();
            break;

        case "ArrowLeft":
            nextPage();
            break;

        case "d":
            prevPage();
            break;

        case "a":
            nextPage();
            break;

        case "F":
            zoomFitToWidth();
            break;

        case "f":
            zoomFitToScreen();
            break;

        case " ":
            nextPage();
            break;

        case "Backspace":
            prevPage();
            break;

        case "0":
            firstPage();
            break;

        case "1":
            lastPage();
            break;

        case ".":
            zoomDefault();
            break;
    }
});"""


def inject(html, injection_site, injection, multiline=False, lines=1):
    splits = html.split(injection_site)
    if len(splits) != 2:
        print(f"{name()}: ERROR '{sys.argv[1]}' is likely not a mokuro html file.")
        exit(1)

    if multiline:
        html = splits[0] + injection + '\n' + '\n'.join(splits[1].split('\n')[lines:])
    else:
        html = splits[0] + injection + splits[1]

    return html


def name():
    return sys.argv[0].split("/")[-1]


def help():
    print(f'Usage: {name()} [MOKURO HTML]')
    print('Injects javascript into mokuro html file.')


def main():
    if '-h' in sys.argv or '--help' in sys.argv:
        help()
        exit(0)

    if len(sys.argv) < 2:
        print(f'{name()}: ERROR Please provide a mokuro html file.')
        print()
        help()
        exit(1)

    html = ''
    try:
        with open(sys.argv[1], 'r') as f:
            html = f.read()
    except:
        print(f"{name()}: ERROR Unable to open file '{sys.argv[1]}'.")
        exit(1)


    # ========================= default settings =============================
    html = inject(html, BACKGROUND_INJECTION_SITE, INJECTION_BACKGROUND, multiline=False)
    html = inject(html, READING_MODE_INJECTION_SITE, INJECTION_READING_MODE, multiline=False)
    # html = inject(html, EDITABLE_INJECTION_SITE, INJECTION_EDITABLE, multiline=False)
    # ========================================================================

    # ===================== disable scroll wheel =================================
    html = inject(html, WHEEL_INJECTION_SITE, INJECTION_WHEEL, multiline=True, lines=4)
    # =============================================================================

    # ========================= disable panzoom ===================================
    # html = inject(html, PANZOOM_INJECTION_SITE, INJECTION_PANZOOM, multiline=True, lines=7)
    # =============================================================================

    # ========================= keyboard shortcuts ===================================
    html = inject(html, KEYBOARD_INJECTION_SITE, INJECTION_KEYBOARD, multiline=True, lines=23)
    # ================================================================================

    # ========================= vim navigation shortcuts =============================
    html = inject(html, VIM_INJECTION_SITE, INJECTION_VIM, multiline=False)
    # ================================================================================

    dir_split = sys.argv[1].split('/')
    if len(dir_split) < 2:
        save_name = f'injected-{dir_split[0]}'
    else:
        save_name = f'{"/".join(dir_split[:-1])}/injected-{dir_split[-1]}'

    with open(save_name, 'w') as f:
        f.write(html)

    print(f"Saved to '{save_name}'")


if __name__ == '__main__':
    main()
