#!/bin/bash
#sadd: seek and destroy - compress all cbz with 'sadd' into jxl

set -e

LOGFILE='sadd.log'

RED='\033[1;31m'
GRN='\033[1;32m'
PRP='\033[1;35m'
NC='\033[0m'

EFFORT=10
DISTANCE=25

usage() {
    echo "USAGE: $(basename "$0") [DIR]"
    echo
    echo "Make sure to rename all cbz to be targeted."
    echo "FILENAME.sadd.cbz"
}

# kill all cjxl processes on exit
function cleanup {
    echo
    if [[ -n $(pgrep -f 'cjxl') ]]; then
        echo -e "${GRN}Killing cjxl processes...${NC}"
        pkill -f cjxl
    fi
}

trap cleanup EXIT

# check if at least one argument
dr="${1}"
if [ $# -lt 1 ]; then
    dr="${PWD}"
fi

# check if directory exists
if [ ! -d "${dr}" ]; then
    echo "ERROR: directory '${1}' doesn't exist."
    usage
    exit 1
fi

echo
echo -e "${GRN}Searching for SADD.CBZ files...$total${NC}"

targetn=$(find -L "${dr}" -type f -name "*.sadd.cbz" -print)

# exit if no targets found
if [ -z "$targetn" ]; then
    echo -e "${RED}NO SADD.CBZ TARGETS FOUND.${NC}"
    exit
fi

# sometimes they're symlinks, sometimes they're not...
# remove the duplicates if symlinks point to same files
targets=$(echo "$targetn" | grep -v '^$' | xargs -n1 -d $'\n' readlink -f | sort -uV)
total=$(echo "$targets" | wc -l)

echo -e "${RED}SADD.CBZ TARGETS FOUND: $total${NC}"

echo
echo -en "${PRP}[PRESS ENTER TO REVIEW]${NC}"
read -r
echo "$targets" | xargs -n1 -d $'\n' basename | batcat --file-name "SADD.CBZ Targets"

echo
echo -en "${RED}Continue? [Y/n] ${NC}"
read -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]] && [ -n "$REPLY" ]
then
    echo
    echo -e "${PRP}Goodbye.${NC}"
    exit 0
fi

# restart log file
: > $LOGFILE

IFS=$'\n'
count=0
for target in ${targets}; do

    echo
    count=$((count+1))

    # run cbz2jxl
    echo -e "${PRP}RUNNING: cbz2jxl -e $EFFORT -d $DISTANCE [$count / $total]${NC}"
    cbz2jxl -e $EFFORT -d $DISTANCE "${target}" 2>&1 | tee -a $LOGFILE

    # rename sadd.cbz -> cbz
    echo -e "${PRP}RENAMING: mv -v ${target} ${target%.sadd.cbz}.done.cbz${NC}"
    mv -v "${target}" "${target%.sadd.cbz}.done.cbz" 2>&1 | tee -a $LOGFILE

    # rename sadd.jxl.cbz -> jxl.cbz
    echo -e "${PRP}RENAMING: mv -v ${target%.sadd.cbz}.jxl ${target%.sadd.jxl.cbz}.jxl.cbz${NC}"
    mv -v "${target%.sadd.cbz}.sadd.jxl.cbz" "${target%.sadd.cbz}.jxl.cbz" 2>&1 | tee -a $LOGFILE

done

unset IFS
