#!/bin/bash

# typ: a vim typing test

# Printing with color
COLOR='\033[0;32m'
NOCOL='\033[0m'

# Create typing test from existing files in SPEECHDIR directory
SPEECHDIR="/home/ddmin/Documents/Text"
SPEECH="$(ls $SPEECHDIR | shuf -n 1)"
TYPE="/tmp/$SPEECH"

# Generate a random line number
LIN=$(wc -l "$SPEECHDIR/$SPEECH")
LIN=$(echo $LIN | cut -d ' ' -f 1)
LIN=$(($LIN-5))

FIRST=$((1 + RANDOM % LIN))
LAST=$((FIRST + 5))

# Delete file if it already exists
rm -rf "$TYPE"

# Generate 5 random lines from the file
WORDS=$(sed -n "$FIRST,$LAST"p "$SPEECHDIR/$SPEECH")

# Create a new file with blank lines in between each line
sed -n "$FIRST,$LAST"p "$SPEECHDIR/$SPEECH" | while read line
do
    echo "$line" >> "$TYPE"
    echo "" >> "$TYPE"
done

# Start timer
echo -e "${COLOR}Current Document: $SPEECH${NOCOL}"
START=$SECONDS

# Open file in Vim buffer
vim "$TYPE"

# Stop timer
DUR=$(( SECONDS - START ))

# Calculate total number of words
NUM=$(echo $WORDS | wc -w)

# File to store the actual test
ACT="/tmp/act"

# File to store the user-typed comparison
COMP="/tmp/comp"

rm -rf "$COMP"
rm -rf "$ACT"

echo "$WORDS" > "$ACT"

# Ending message
for i in {2..17..3};
do
    sed -n "$i"p "$TYPE" >> "$COMP"
done

if cmp -s "$COMP" "$ACT";
then
    RATIO=$(echo "$DUR / $NUM" | bc -l | cut -c -4)
    echo -e "You typed all ${COLOR}$NUM words${NOCOL} in ${COLOR}$DUR seconds${NOCOL}! ($RATIO WPS)"
else
    echo -e "It took you ${COLOR}$DUR seconds${NOCOL}, but you did not type all ${COLOR}$NUM words${NOCOL} correctly."
    echo
    echo -e "${COLOR}Here are your mistakes:${NOCOL}"
    diff "$COMP" "$ACT" | sed '1'd
fi
