#!/bin/bash
# sync github directories

GREEN='\033[1;32m'
NC='\033[0m'

CONFIG="$HOME/.config"
GITHUB="$HOME/.local/drive/code"

# I guess I can just make symlinks

# GITHUB_CONFIG="$GITHUB/dotfiles/config"
# sync files from local machine -> github directory
# CONFIGS=("doom" "zathura" "ranger" "mpv")
# for config in ${CONFIGS[@]}
# do
#     yes | cp -r $CONFIG/$config/* $GITHUB_CONFIG/$config/
# done

# check for changes in remote/local
for gitdir in `find $GITHUB -name .git -type d -prune | sort -V`
do
    dir=$(dirname $gitdir)
    echo -e "${GREEN}DIRECTORY: $dir$NC"
    cd $dir
    # git pull origin master
    git status $dir
    echo
done
