#!/bin/bash

# Fill in the blanks

# KEEPASSXC="<KeePassXC binary/appimage>"
# DATABASE="<Password Database>"
#
# KEYFILE_GPG="<Keyfile GPG Location>"
#
# KEYFILE_ATTR="<Keyfile Attribute>"
# DATABASE_ATTR="<Database Attribute>"

. $HOME/.env

KEYFILE="/tmp/$(tr -cd 'a-f0-9' < /dev/urandom | head -c 32)-keyfile"

notify-send "keepassxc" --icon=keepassxc "Starting keepassxc"

secret-tool lookup "$KEYFILE_ATTR" "$KEYFILE_GPG" | gpg --batch --passphrase-fd 0 --decrypt "$KEYFILE_GPG" > "$KEYFILE"
secret-tool lookup "$DATABASE_ATTR" "$DATABASE" | "$KEEPASSXC" --pw-stdin "$DATABASE" --keyfile "$KEYFILE"
# shred -vzun 3 "$KEYFILE"
