#!/bin/bash

# connect-earbud: connect wireless earbuds

# read bluetooth device from $BT_EARBUD
. $HOME/.env

rfkill unblock bluetooth

CONNECT=$(bluetoothctl info $BT_EARBUD | sed -n -e 's/Connected://p')

if [ $CONNECT == "no" ]; then
    printf "📶 "
    bluetoothctl --timeout 2 connect $BT_EARBUD

else
    printf "📶 "
    bluetoothctl --timeout 2 disconnect $BT_EARBUD
fi
