#!/bin/bash

# connect-earbud: connect wireless earbuds

rfkill unblock bluetooth
DEVICE="AB:27:C2:24:56:D0"

CONNECT=$(bluetoothctl info $DEVICE | sed -n -e 's/Connected://p')

if [ $CONNECT == "no" ]; then
    printf "📶 "
    bluetoothctl --timeout 2 connect $DEVICE

else
    printf "📶 "
    bluetoothctl --timeout 2 disconnect $DEVICE
fi
